[build]
  command = "npm run build"
  functions = "lambda"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
  VUE_APP_BACKEND_URL = "http://localhost:8000"
  DJANGO_SETTINGS_MODULE = "aquaponics_django.aquaponics_django.settings"
