[build]
  command = "npm run build"
  functions = "functions"

[build.command]
  command = "python ../aquaponics_django/manage.py collectstatic --noinput && python ../aquaponics_django/manage.py runserver"


[build.environment]
  DJANGO_SETTINGS_MODULE = "aquaponics_django.settings"
  PYTHONPATH = "."


[context.production.environment]
  SPA_ROOT = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.env]
  DJANGO_SECRET_KEY = "django-insecure-^6ekph@1s&@o_9mknq=n8fj%-@#5t^=4ayenw*6-3)izaag@hu"

[build.environment]
  PIP_INSTALL = "true"
  PIP_REQUIREMENTS = "requirements.txt"

