# Generated by Django 4.0.4 on 2022-05-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(help_text='El nombre del cultivo.', max_length=70)),
                ('tipo', models.CharField(help_text='El tipo de cultivo.', max_length=30)),
                ('t_min', models.FloatField(max_length=10, verbose_name='La temperatura minima del cultivo.')),
                ('t_max', models.FloatField(max_length=10, verbose_name='La temperatura maxima del cultivo.')),
                ('t_opt', models.FloatField(max_length=10, verbose_name='La temperatura optima del cultivo.')),
                ('germinacion_1', models.IntegerField(max_length=255, verbose_name='Tiempo en dias de primera cosecha.')),
                ('germinacion_n', models.IntegerField(max_length=255, verbose_name='Tiempo en dias entre cosechas.')),
                ('distancia', models.FloatField(help_text='Separacion entre plantas del cultvo.', max_length=10)),
                ('primera_cosecha', models.FloatField(help_text='Numero de meses para la primera cosecha.', max_length=10)),
                ('n_cosechas', models.FloatField(help_text='Numero de cosechas al año.', max_length=10)),
                ('distanciaXcosechaAnual', models.FloatField(max_length=10, verbose_name='Distancia por cosecha anual.')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(help_text='El nombre del municipio', max_length=70)),
                ('departamento', models.CharField(help_text='Nombre del departamento del municipio.', max_length=70)),
                ('t_min', models.FloatField(help_text='Temperatura minima del municipio.', max_length=30)),
                ('t_avg', models.FloatField(help_text='Temperatura promedio del municipio.', max_length=30)),
                ('t_max', models.FloatField(help_text='Temperatura maxima del municipio.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipiosCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.cultivo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='municipios',
            field=models.ManyToManyField(through='simulator.MunicipiosCultivo', to='simulator.municipio'),
        ),
    ]
