[build]
  command = "npm run build"
  functions-dir = "functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  DJANGO_SETTINGS_MODULE = "aquaponics_django.settings"

[build.command]
  script = "ls & sh ../setup.sh"

[dev]
  command = "npm run serve"
